### ISSUE TITLE
Provider crashes on `GrantPrivilegesToRole` resource

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-snowflake#328]
### What happened?

Got a panic when using the `GrantPrivilegesToRole` resource.

Crash output:

```sh
Diagnostics:
  snowflake:index:GrantPrivilegesToRole (table_future_grant):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (3927-snowflake-grantprivilegestorole-ringo):
    panic: runtime error: index out of range [1] with length 1
    goroutine 44 [running]:
    github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewDatabaseObjectIdentifierFromFullyQualifiedName({0x14000c4cb90?, 0x14000c58f30?})
        /home/runner/go/pkg/mod/github.com/!snowflake-!labs/terraform-provider-snowflake@v0.70.0/pkg/sdk/identifier_helpers.go:149 +0xb8
    github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.configureAccountRoleGrantPrivilegeOptions(0x1400051b640?, {0x14000c70640, 0x1, 0x1}, 0xf8?, 0x14000c14fe8)
        /home/runner/go/pkg/mod/github.com/!snowflake-!labs/terraform-provider-snowflake@v0.70.0/pkg/resources/grant_privileges_to_role.go:779 +0x1330
    github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateGrantPrivilegesToRole(0x101f92be0?, {0x1021bb380?, 0x140006adad0?})
        /home/runner/go/pkg/mod/github.com/!snowflake-!labs/terraform-provider-snowflake@v0.70.0/pkg/resources/grant_privileges_to_role.go:453 +0x138
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1021f6bb8?, {0x1021f6bb8?, 0x1400003e0a8?}, 0xd?, {0x1021bb380?, 0x140006adad0?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230710100801-03a71d0fca3d/helper/schema/resource.go:726 +0x134
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000778ee0, {0x1021f6bb8, 0x1400003e0a8}, 0x0, 0x14000b28c80, {0x1021bb380, 0x140006adad0})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230710100801-03a71d0fca3d/helper/schema/resource.go:869 +0x874
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x140001b3f80?, {0x0?, 0x14000c15570?, 0x10217db80?}}, {0x101ad620b, 0x22}, {0x0?, 0x0}, {0x1021ffe98?, 0x14000b28c80})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.57.0/pkg/tfshim/sdk-v2/provider.go:100 +0x154
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x140005c5b80, {0x1021f6c28?, 0x14000e3b710?}, 0x14000f13e50)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.57.0/pkg/tfbridge/provider.go:752 +0x4f8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x1021f6c28, 0x14000e3b710}, {0x1020f3ca0?, 0x14000f13e50})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.76.1/proto/go/provider_grpc.pb.go:573 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1021f6c28, 0x14000e3b1a0}, {0x1020f3ca0, 0x14000f13e50}, 0x1400051a780, 0x14000590738)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x102199320?, 0x140005c5b80}, {0x1021f6c28, 0x14000e3b1a0}, 0x140009bb420, 0x14000d81f80)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.76.1/proto/go/provider_grpc.pb.go:575 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x14000676960, {0x102200560, 0x140006ca340}, 0x14000c39e60, 0x14000e5dc20, 0x102f581a0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1337 +0xc28
    google.golang.org/grpc.(*Server).handleStream(0x14000676960, {0x102200560, 0x140006ca340}, 0x14000c39e60, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1714 +0x80c
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:959 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:957 +0x164

    error: update failed
```

### Expected Behavior

Pulumi complaining the input values are not correct, but definitely no crash. In this case, the problem lies in the `schema_name` value not correct. The upstream TF issue (see link below) contains a comment that the fully qualified schema object name also needs to be quoted.

So not:

```
<database_name>.<schema_name>
```

but:

```
"<database_name>"."<schema_name>"
```

### Steps to reproduce

This resource leads to the provider crashing:

```python
GrantPrivilegesToRole(
    resource_name="schema_grant",
    on_schema=GrantPrivilegesToRoleOnSchemaArgs(schema_name=f"{database_name)}.{schema_name}"),
    privileges=["USAGE"],
    role_name=role_name,
    with_grant_option=False,
)
```

### Output of `pulumi about`

```sh
CLI          
Version      3.80.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME       VERSION
python     unknown
snowflake  0.32.0

Host     
OS       darwin
Version  13.5.1
Arch     arm64

Dependencies:
NAME              VERSION
pip               23.2.1
pulumi-snowflake  0.32.0
setuptools        68.1.2
wheel             0.41.2
```

### Additional context

Upstream issue: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1999

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Upstream issue seems to be fixed. This might be close-able.

**Comment by VenelinMartinov** [comment]
Can't repro this on the originally reported 0.32.0.

I tried with the following program:

```python
"""A Python Pulumi program"""

import pulumi

import pulumi_snowflake as snowflake

simple = snowflake.Database(
    "simple", comment="test comment", data_retention_time_in_days=1
)

db_role = snowflake.DatabaseRole(
    "dbRole",
    comment="my db role",
    database=simple.name,
)

schema = snowflake.Schema(
    "schema",
    comment="A schema.",
    data_retention_days=1,
    database=simple.name,
    is_managed=False,
    is_transient=False,
)

schema_name = pulumi.Output.all(simple.name, schema.name).apply(
    lambda args: f"{args[0]}.{args[1]}"
)

snowflake.GrantPrivilegesToRole(
    resource_name="schema_grant",
    on_schema=snowflake.GrantPrivilegesToRoleOnSchemaArgs(schema_name=schema_name),
    privileges=["USAGE"],
    role_name=db_role.name,
    with_grant_option=False,
)

```

**Comment by ringods** [comment]
@VenelinMartinov yes I have. Below is the program where I added the additional quotes to prevent the crash from happening. If you remove that quoting from the program, you have the program used to reproduce the crash back then.

```python
"""Test new GrantPrivilegesToRole resource in Snowflake"""

from pulumi import *
from pulumi_snowflake import *
from pulumi_snowflake.schema import *

database_name = "ringo-zd3927"
role_name = "SYSADMIN"
schema_name = "schema"

database = Database(database_name)

schema = Schema(schema_name, database=database.name, comment="Dummy schema")

###

full_schema_name = Output.concat("\"", database.name, "\".\"", schema.name, "\"")

s = GrantPrivilegesToRoleOnSchemaArgs(schema_name=full_schema_name)

GrantPrivilegesToRole(
    resource_name="schema_grant",
    on_schema=s,
    privileges=["USAGE"],
    role_name=role_name,
    with_grant_option=False,
    opts=ResourceOptions(parent=schema),
)

###

a = GrantPrivilegesToRoleOnSchemaObjectAllArgs(
    object_type_plural="TABLES", in_database=Output.concat("\"", database.name, "\"") #, in_schema=schema.name
)
t1 = GrantPrivilegesToRoleOnSchemaObjectArgs(all=a)

GrantPrivilegesToRole(
    resource_name="table_all_grant",
    on_schema_object=t1,
    privileges=["SELECT"],
    role_name=role_name,
    with_grant_option=False,
    opts=ResourceOptions(parent=schema),
)

###

f = GrantPrivilegesToRoleOnSchemaObjectFutureArgs(
    object_type_plural="TABLES", in_schema=full_schema_name
)
t2 = GrantPrivilegesToRoleOnSchemaObjectArgs(future=f)

GrantPrivilegesToRole(
    resource_name="table_future_grant",
    on_schema_object=t2,
    privileges=["SELECT"],
    role_name=role_name,
    with_grant_option=False,
    opts=ResourceOptions(parent=schema),
)

```

**Comment by ringods** [comment]
Solution is to properly quote the schema object. The string value needs to be of the form:

`"<database_name>"."<schema_name>"."<object_name>"`

#717 is filed to make sure this info is properly copied over from the TF docs.
